### ISSUE TITLE
Can compile on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by mwozny123** [uglyDwarf/evdevshift#7]
Can compile on new Ubuntu 16.04 LTS:

> $ make
> cc  -g -Wall -Wextra -Werror  -c -o config_lex.o config_lex.c
> config_lex.c: In function 'yy_get_next_buffer':
> config_lex.c:1167:44: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
>   if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_s
>                                             ^
> cc1: all warnings being treated as errors
> <builtin>: recipe for target 'config_lex.o' failed
> make: **\* [config_lex.o] Error 1

**Comment by uglyDwarf** [comment]
Hi,
can you try editing the Makefile and remove the -Werror option from CPPFLAGS?
It should leave the warning as warning, so it should compile...
Kind regards,
Michal

**Comment by mwozny123** [comment]
Now works:) Thanks:)

Could you commit that change or should I commit it (and create pull request)?

**Comment by uglyDwarf** [comment]
In the next few days I'm going to install 16.04, and then I'll investigate this thing further - until then this can be used as a workaround...
Kind regards,
Michal

**Comment by mwozny123** [comment]
Now compiles. Closing
